export const ActionType = {
    ALL_SOCIAL_PLATFORM: "ALL_SOCIAL_PLATFORM",
    SET_VOLUME: "SET_VOLUME",
    REMOVE_NOTIFICATION_FOR_MESSAGE: "REMOVE_NOTIFICATION_FOR_MESSAGE",
    SET_ALL_LEADS_LIST: "SET_ALL_LEADS_LIST",
    SET_NOTIFICATION_STATE: "SET_NOTIFICATION_STATE",
    IS_TYPING_ACTION: "IS_TYPING_ACTION",
    SET_SOCKET_SEND_PEER_GROUP_CALL_MESSAGE: "SET_SOCKET_SEND_PEER_GROUP_CALL_MESSAGE",
    SET_GROUP_INTERNALCALLACTION: "SET_GROUP_INTERNALCALLACTION",
    SET_INCOMING_GROUP_CALL: "SET_INCOMING_GROUP_CALL",
    RECEIVEED_GROUP_CALL: "RECEIVEED_GROUP_CALL"
}