name: DeployJS

on:
  push:
    branches:
      - Developement  # Corrected branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Optional: Remove if not needed for other steps
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Debian Server and Build React App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e  # Exit immediately if a command exits with a non-zero status
            set -x  # Print each command before executing it

            # Navigate to the deployment directory
            cd ${{ secrets.DEPLOY_PATH }}

            # Configure Git to trust this directory
            git config --global --add safe.directory ${{ secrets.DEPLOY_PATH }}

            # Check if the directory is a Git repository
            if [ -d ".git" ]; then
              echo "Git repository found. Pulling latest changes."
              git pull origin Developement
            else
              echo "Git repository not found. Cloning repository."
              git clone git@github.com:AngelPbx/UcaaS-Frontend.git . 
              git checkout Developement
            fi

            # Install dependencies
            npm install

            # Build the React app
            npm run build

            # Reload Apache to serve the new build
            sudo systemctl reload apache2

            exit
          EOF
