name: DeployJS

on:
  push:
    branches:
      - Developement  # Adjust this to your preferred branch (e.g., 'dev', 'staging', etc.)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Debian Server and Build React App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Navigate to the directory where the React app is located
            cd ${{ secrets.DEPLOY_PATH }}

             # Check if the directory is a Git repository
              if [ -d ".git" ]; then
                echo "Git repository found. Pulling latest changes."
                git config --global --add safe.directory ${{ secrets.DEPLOY_PATH }}
                git pull origin Developement
              else
                echo "Git repository not found. Cloning repository."
                git clone https://github.com/AngelPbx/UcaaS-Frontend.git . 
                # Replace <YOUR_GIT_REPO_URL> with your actual repository URL
                git checkout Develoepment
              fi

            # Ensure correct ownership and permissions (if passwordless sudo is configured)
            # sudo chown -R $USER:$USER .
            # sudo chmod -R u+w .

            # Pull the latest changes from the Git repository
            sudo git pull origin Developement  # Replace 'main' with your branch if needed

            # Install any new dependencies (if required)
            # npm install  # Uncomment if you want to run npm install before the build

            # Build the React app
            sudo npm run build

            # Restart Apache to serve the new build (optional)
            sudo systemctl reload apache2
            
            exit
          EOF
